name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install pipenv
      run: pip install pipenv
    - name: Create Pipenv environment
      run: |
        cd ml_train
        pipenv install --ignore-pipfile
        cd ..
    - name: Run script using pipenv environment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PIPENV_PIPFILE: ${{ github.workspace }}/ml_train/Pipfile
      run: |
        cd ml_serve
        pipenv run python serve_fare_prediction_aws_cicd.py
