name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: |
        cd ml_train
        pipenv install --ignore-pipfile
        cd ..
    - name: Set up environment variables for MLflow server
      run: |
        echo "DB_USER=mlflow" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
        echo "DB_ENDPOINT=mlflow-database.cu8izfgsiwpi.us-east-1.rds.amazonaws.com" >> $GITHUB_ENV
        echo "DB_NAME=mlflow_db" >> $GITHUB_ENV
        echo "S3_BUCKET_NAME=mlflow-artifacts-remote-ahm-amm" >> $GITHUB_ENV
    - name: Start MLflow server in background
      run: |
        nohup mlflow server -h 0.0.0.0 -p 5000 --backend-store-uri postgresql://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@${{ env.DB_ENDPOINT }}:5432/${{ env.DB_NAME }} --default-artifact-root s3://${{ env.S3_BUCKET_NAME }} &
    - name: Run script using pipenv environment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd ml_serve
        pipenv run python serve_fare_prediction_aws_cicd.py
